/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaInterfaz;

import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import agenda.Contacto;
import agenda.Familia;
import agenda.Trabajo;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Usuario
 */
public class CrearContactoGUI extends javax.swing.JFrame {

    public static ArrayList<Contacto> contactos = new ArrayList<Contacto>();
    DefaultTableModel modeloT = new DefaultTableModel();
    JFileChooser selecArchivo = new JFileChooser();
    File archivo;
    boolean setFiltros = false;
    Workbook wb;

    /**
     * Creates new form CrearContactoGUI
     */
    public CrearContactoGUI() {
        initComponents();
        jtbContactosFlia.setModel(modeloT);
        jtbContactosTrab.setModel(modeloT);
        modeloT.addColumn("Nombre 1");
        modeloT.addColumn("Nombre 2");
        modeloT.addColumn("Apellido 1");
        modeloT.addColumn("Apellido 2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtpPanelGral = new javax.swing.JTabbedPane();
        jpInfoGral = new javax.swing.JPanel();
        jlblNombres = new javax.swing.JLabel();
        jtxtNombres1 = new javax.swing.JTextField();
        jtxtNombres2 = new javax.swing.JTextField();
        jlblApellidos1 = new javax.swing.JLabel();
        jtxtApellidos1 = new javax.swing.JTextField();
        jtxtApellidos2 = new javax.swing.JTextField();
        jlblTelefono = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jlblGenero = new javax.swing.JLabel();
        jtxtGenero = new javax.swing.JTextField();
        jtxtEstadoCiv = new javax.swing.JTextField();
        jlblEstadoCiv = new javax.swing.JLabel();
        jtxtFechaNac = new javax.swing.JTextField();
        jlblFechaNac = new javax.swing.JLabel();
        jtxtDocumento = new javax.swing.JTextField();
        jlblDocumento = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        jlblDireccion = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jlblCiudad = new javax.swing.JLabel();
        jtxtCiudad = new javax.swing.JTextField();
        jtxtProfesion = new javax.swing.JTextField();
        jlblProfesion = new javax.swing.JLabel();
        jbtnLimpiar = new javax.swing.JButton();
        jbtnSiguiente = new javax.swing.JButton();
        jpTrabajo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbtnGuardarTra = new javax.swing.JButton();
        jlblNombreEmpresa = new javax.swing.JLabel();
        jtxtNombreEmpresa = new javax.swing.JTextField();
        jtxtCargo = new javax.swing.JTextField();
        jlblCargo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbContactosTrab = new javax.swing.JTable();
        jpFamilia = new javax.swing.JPanel();
        jtxtApodo = new javax.swing.JTextField();
        jlblApodo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jtxtParentesco = new javax.swing.JTextField();
        jlblParentesco = new javax.swing.JLabel();
        jbtnGuardarFlia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbContactosFlia = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiBuscar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jtpPanelGral.setName("jtbpPanelPestanas"); // NOI18N

        jlblNombres.setText("Nombres");

        jtxtNombres1.setToolTipText("");

        jtxtNombres2.setToolTipText("");

        jlblApellidos1.setText("Apellidos");

        jtxtApellidos1.setToolTipText("");

        jtxtApellidos2.setToolTipText("");

        jlblTelefono.setText("Telefono");

        jtxtTelefono.setToolTipText("");

        jlblGenero.setText("Genero");

        jtxtGenero.setToolTipText("");

        jtxtEstadoCiv.setToolTipText("");

        jlblEstadoCiv.setText("Estado civil");

        jtxtFechaNac.setToolTipText("");

        jlblFechaNac.setText("Fecha nacimiento");

        jtxtDocumento.setToolTipText("");

        jlblDocumento.setText("N° Documento");

        jtxtEmail.setToolTipText("");

        jlblEmail.setText("Email");

        jlblDireccion.setText("Direccion");

        jtxtDireccion.setToolTipText("");

        jlblCiudad.setText("Ciudad");

        jtxtCiudad.setToolTipText("");

        jtxtProfesion.setToolTipText("");

        jlblProfesion.setText("Profesion");

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnLimpiarMouseClicked(evt);
            }
        });

        jbtnSiguiente.setText("Siguiente >");
        jbtnSiguiente.setToolTipText("");
        jbtnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSiguienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpInfoGralLayout = new javax.swing.GroupLayout(jpInfoGral);
        jpInfoGral.setLayout(jpInfoGralLayout);
        jpInfoGralLayout.setHorizontalGroup(
            jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoGralLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblGenero)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblEstadoCiv)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblFechaNac)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblDocumento)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblCiudad)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addComponent(jlblProfesion)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpInfoGralLayout.createSequentialGroup()
                            .addComponent(jlblNombres)
                            .addGap(18, 18, 18)
                            .addComponent(jtxtNombres1))
                        .addGroup(jpInfoGralLayout.createSequentialGroup()
                            .addComponent(jlblApellidos1)
                            .addGap(18, 18, 18)
                            .addComponent(jtxtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jbtnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnSiguiente)
                        .addGap(17, 17, 17))
                    .addGroup(jpInfoGralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNombres2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jtxtApellidos2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpInfoGralLayout.setVerticalGroup(
            jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInfoGralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNombres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtApellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblApellidos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblFechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEstadoCiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblProfesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jpInfoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLimpiar)
                    .addComponent(jbtnSiguiente))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jtpPanelGral.addTab("Info General", jpInfoGral);

        jButton1.setText("< Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnGuardarTra.setText("Guardar");
        jbtnGuardarTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnGuardarTraMouseClicked(evt);
            }
        });

        jlblNombreEmpresa.setText("Nombre Empresa");

        jtxtNombreEmpresa.setToolTipText("");

        jtxtCargo.setToolTipText("");

        jlblCargo.setText("Cargo");

        jLabel2.setText("Contactos de trabajo agregados");

        jtbContactosTrab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbContactosTrab);

        javax.swing.GroupLayout jpTrabajoLayout = new javax.swing.GroupLayout(jpTrabajo);
        jpTrabajo.setLayout(jpTrabajoLayout);
        jpTrabajoLayout.setHorizontalGroup(
            jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrabajoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTrabajoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jpTrabajoLayout.createSequentialGroup()
                        .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpTrabajoLayout.createSequentialGroup()
                                .addComponent(jlblNombreEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpTrabajoLayout.createSequentialGroup()
                                .addComponent(jlblCargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(267, Short.MAX_VALUE))
                    .addGroup(jpTrabajoLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnGuardarTra)
                        .addGap(20, 20, 20))))
            .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpTrabajoLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        jpTrabajoLayout.setVerticalGroup(
            jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTrabajoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombreEmpresa)
                    .addComponent(jtxtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCargo)
                    .addComponent(jtxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardarTra)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
            .addGroup(jpTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpTrabajoLayout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addComponent(jLabel2)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );

        jtpPanelGral.addTab("Trabajo", jpTrabajo);

        jpFamilia.setEnabled(false);

        jtxtApodo.setToolTipText("");

        jlblApodo.setText("Apodo");

        jButton2.setText("< Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtxtParentesco.setToolTipText("");

        jlblParentesco.setText("Parentesco");

        jbtnGuardarFlia.setText("Guardar");
        jbtnGuardarFlia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnGuardarFliaMouseClicked(evt);
            }
        });

        jLabel1.setText("Contactos familiares agregados");

        jtbContactosFlia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbContactosFlia);

        javax.swing.GroupLayout jpFamiliaLayout = new javax.swing.GroupLayout(jpFamilia);
        jpFamilia.setLayout(jpFamiliaLayout);
        jpFamiliaLayout.setHorizontalGroup(
            jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFamiliaLayout.createSequentialGroup()
                .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFamiliaLayout.createSequentialGroup()
                        .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFamiliaLayout.createSequentialGroup()
                                .addComponent(jlblParentesco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpFamiliaLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jButton2))
                                .addGroup(jpFamiliaLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jlblApodo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(jbtnGuardarFlia))
                    .addGroup(jpFamiliaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpFamiliaLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane2)
                    .addGap(21, 21, 21)))
        );
        jpFamiliaLayout.setVerticalGroup(
            jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFamiliaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblApodo)
                    .addComponent(jtxtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblParentesco)
                    .addComponent(jtxtParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jbtnGuardarFlia))
                .addGap(20, 20, 20))
            .addGroup(jpFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpFamiliaLayout.createSequentialGroup()
                    .addGap(248, 248, 248)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        jtpPanelGral.addTab("Familia", jpFamilia);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jmiBuscar.setText("Buscar");
        jmiBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(jmiBuscar);

        jMenuItem2.setText("Volver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Exportar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jtpPanelGral, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtpPanelGral)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jtpPanelGral.getAccessibleContext().setAccessibleName("");
        jtpPanelGral.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnLimpiarMouseClicked
        for (Component controlActual : jpInfoGral.getComponents()) {
            if (controlActual instanceof JTextField) {
                ((JTextComponent) controlActual).setText("");
            }
        }
    }//GEN-LAST:event_jbtnLimpiarMouseClicked

    private void jbtnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSiguienteMouseClicked

        switch (this.getTitle()) {
            case "Familia":
                if (validar(1)) {
                    jtpPanelGral.add(jpFamilia);
                    jtpPanelGral.setTitleAt(1, "Familia");
                    jtpPanelGral.setSelectedIndex(1);
                } else {
                    JOptionPane.showMessageDialog(null, "Debe diligenciar la informacion requerida");
                }
                break;
            case "Trabajo":
                if (validar(1)) {
                    jtpPanelGral.add(jpTrabajo);
                    jtpPanelGral.setTitleAt(1, "Trabajo");
                    jtpPanelGral.setSelectedIndex(1);
                } else {
                    JOptionPane.showMessageDialog(null, "Debe diligenciar la informacion requerida");
                }
                break;
        }
        llenarComboBox();
    }//GEN-LAST:event_jbtnSiguienteMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PpalScreenGUI cf = new PpalScreenGUI();
        dispose();
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtpPanelGral.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnGuardarFliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGuardarFliaMouseClicked
        if (validar(2)) {
            guardar(1);
        } else {
            JOptionPane.showMessageDialog(null, "Debe diligenciar la informacion requerida");
        }
    }//GEN-LAST:event_jbtnGuardarFliaMouseClicked

    private void jmiBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarActionPerformed
        BusquedaGUI cf = new BusquedaGUI();
        dispose();
        cf.setVisible(true);
    }//GEN-LAST:event_jmiBuscarActionPerformed

    private void jbtnGuardarTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGuardarTraMouseClicked
        if (validar(3)) {
            guardar(2);
        } else {
            JOptionPane.showMessageDialog(null, "Debe diligenciar la informacion requerida");
        }
    }//GEN-LAST:event_jbtnGuardarTraMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtpPanelGral.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (selecArchivo.showDialog(null, "Exportar") == JFileChooser.APPROVE_OPTION) {
            archivo = selecArchivo.getSelectedFile();
            if (archivo.getName().endsWith("xls") || archivo.getName().endsWith("xlsx")) {
                JOptionPane.showMessageDialog(null, Exportar(archivo, jtbContactosFlia) + "\n Formato ." + archivo.getName().substring(archivo.getName().lastIndexOf(".") + 1));
            } else {
                JOptionPane.showMessageDialog(null, "Elija un formato valido.");
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void buscar(Contacto contacto) {
        Object[] listaColumna = new Object[4];
        jtxtApellidos1.setText(contacto.getApellido1());
        jtxtApellidos2.setText(contacto.getApellido2());
        jtxtNombres1.setText(contacto.getNombre1());
        jtxtNombres2.setText(contacto.getNombre2());
        jtxtDireccion.setText(contacto.getDireccion());
        jtxtCiudad.setText(contacto.getCiudad());
        jtxtDocumento.setText(contacto.getDocumento());
        jtxtFechaNac.setText(contacto.getFechaNacimiento());
        jtxtEmail.setText(contacto.getEmail());
        jtxtTelefono.setText(contacto.getCelular());
        jtxtGenero.setText(contacto.getGenero());
        jtxtEstadoCiv.setText(contacto.getEstado());
        jtxtProfesion.setText(contacto.getProfesion());
        listaColumna[0] = jtxtNombres1.getText();
        listaColumna[1] = jtxtNombres2.getText();
        listaColumna[2] = jtxtApellidos1.getText();
        listaColumna[3] = jtxtApellidos2.getText();
        modeloT.addRow(listaColumna);
        if (contacto instanceof Familia) {
            jtxtParentesco.setText(((Familia) contacto).getParentesco());
            jtxtApodo.setText(((Familia) contacto).getApodo());
            jtpPanelGral.remove(jpTrabajo);

        } else if (contacto instanceof Trabajo) {
            jtxtNombreEmpresa.setText(((Trabajo) contacto).getNombreEmpresa());
            jtxtCargo.setText(((Trabajo) contacto).getCargo());
            jtpPanelGral.remove(jpFamilia);
        }
    }

    public String Exportar(File archivo, JTable tablaD) {
        String respuesta = "No se realizo con exito la exportación.";
        int numFila = tablaD.getRowCount(), numColumna = tablaD.getColumnCount();
        if (archivo.getName().endsWith("xls")) {
            wb = new HSSFWorkbook();
        } else {
            wb = new XSSFWorkbook();
        }
        Sheet hoja = wb.createSheet("Pruebita");

        try {
            for (int i = -1; i < numFila; i++) {
                Row fila = hoja.createRow(i + 1);
                for (int j = 0; j < numColumna; j++) {
                    Cell celda = fila.createCell(j);
                    if (i == -1) {
                        celda.setCellValue(String.valueOf(tablaD.getColumnName(j)));
                    } else {
                        celda.setCellValue(String.valueOf(tablaD.getValueAt(i, j)));
                    }
                    wb.write(new FileOutputStream(archivo));
                }
            }
            respuesta = "Exportación exitosa.";
        } catch (Exception e) {
        }
        return respuesta;
    }

    private void setForeColorLabels(JPanel jp) {
        for (Component controlActual : jp.getComponents()) {
            if (controlActual instanceof JLabel) {
                ((JLabel) controlActual).setForeground(Color.BLACK);
            }
        }
    }

    private boolean validar(int caso) {
        boolean retorno = true;
        switch (caso) {
            case 1:
                setForeColorLabels(jpInfoGral);
                if (jtxtNombres1.getText().equals("")) {
                    jlblNombres.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtApellidos1.getText().equals("")) {
                    jlblApellidos1.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtTelefono.getText().equals("")) {
                    jlblTelefono.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtEmail.getText().equals("")) {
                    jlblEmail.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtDocumento.getText().equals("")) {
                    jlblDocumento.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtFechaNac.getText().equals("")) {
                    jlblFechaNac.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtEstadoCiv.getText().equals("")) {
                    jlblEstadoCiv.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtGenero.getText().equals("")) {
                    jlblGenero.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtProfesion.getText().equals("")) {
                    jlblProfesion.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtCiudad.getText().equals("")) {
                    jlblCiudad.setForeground(Color.RED);
                    retorno = false;
                }
                break;
            case 2:
                setForeColorLabels(jpFamilia);
                if (jtxtApodo.getText().equals("")) {
                    jlblApodo.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtParentesco.getText().equals("")) {
                    jlblParentesco.setForeground(Color.RED);
                    retorno = false;
                }
                break;
            case 3:
                setForeColorLabels(jpTrabajo);
                if (jtxtNombreEmpresa.getText().equals("")) {
                    jlblNombreEmpresa.setForeground(Color.RED);
                    retorno = false;
                }
                if (jtxtCargo.getText().equals("")) {
                    jlblCargo.setForeground(Color.RED);
                    retorno = false;
                }
                break;
        }
        return retorno;
    }

    private void guardar(int caso) {
        switch (caso) {
            case 1:
                Contacto familia = new Familia(jtxtNombres1.getText(), jtxtNombres2.getText(), jtxtApellidos1.getText(), jtxtApellidos2.getText(), jtxtTelefono.getText(), jtxtEmail.getText(), jtxtDireccion.getText(), 0, jtxtFechaNac.getText(), jtxtCiudad.getText(), jtxtDocumento.getText(), jtxtEstadoCiv.getText(), jtxtProfesion.getText(), jtxtGenero.getText(), jtxtParentesco.getText(), jtxtApodo.getText());
                contactos.add(familia);
                break;
            case 2:
                Contacto trabajo = new Trabajo(jtxtNombres1.getText(), jtxtNombres2.getText(), jtxtApellidos1.getText(), jtxtApellidos2.getText(), jtxtTelefono.getText(), jtxtEmail.getText(), jtxtDireccion.getText(), 0, jtxtFechaNac.getText(), jtxtCiudad.getText(), jtxtDocumento.getText(), jtxtEstadoCiv.getText(), jtxtProfesion.getText(), jtxtGenero.getText(), jtxtNombreEmpresa.getText(), 0, jtxtCargo.getText());
                contactos.add(trabajo);
                break;
        }
        llenarComboBox();
        JOptionPane.showMessageDialog(null, "La informacion fue guardada exitosamente");
    }

    private void llenarComboBox() {
        for (Contacto contacto : contactos) {
            Object[] listaColumna = new Object[4];
            listaColumna[0] = jtxtNombres1.getText();
            listaColumna[1] = jtxtNombres2.getText();
            listaColumna[2] = jtxtApellidos1.getText();
            listaColumna[3] = jtxtApellidos2.getText();
            modeloT.addRow(listaColumna);
            /*if (contacto instanceof Trabajo) {
             jcmbTrabajo.addItem(jtxtNombres1.getText() + " " + jtxtNombres2.getText() + " " + jtxtApellidos1.getText() + " " + jtxtApellidos2.getText());
             } else if (contacto instanceof Familia) {
             jcmbFamiliares.addItem(jtxtNombres1.getText() + " " + jtxtNombres2.getText() + " " + jtxtApellidos1.getText() + " " + jtxtApellidos2.getText());
             }*/
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearContactoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearContactoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearContactoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearContactoGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearContactoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnGuardarFlia;
    private javax.swing.JButton jbtnGuardarTra;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSiguiente;
    private javax.swing.JLabel jlblApellidos1;
    private javax.swing.JLabel jlblApodo;
    private javax.swing.JLabel jlblCargo;
    private javax.swing.JLabel jlblCiudad;
    private javax.swing.JLabel jlblDireccion;
    private javax.swing.JLabel jlblDocumento;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblEstadoCiv;
    private javax.swing.JLabel jlblFechaNac;
    private javax.swing.JLabel jlblGenero;
    private javax.swing.JLabel jlblNombreEmpresa;
    private javax.swing.JLabel jlblNombres;
    private javax.swing.JLabel jlblParentesco;
    private javax.swing.JLabel jlblProfesion;
    private javax.swing.JLabel jlblTelefono;
    private javax.swing.JMenuItem jmiBuscar;
    public javax.swing.JPanel jpFamilia;
    public javax.swing.JPanel jpInfoGral;
    public javax.swing.JPanel jpTrabajo;
    private javax.swing.JTable jtbContactosFlia;
    private javax.swing.JTable jtbContactosTrab;
    public javax.swing.JTabbedPane jtpPanelGral;
    private javax.swing.JTextField jtxtApellidos1;
    private javax.swing.JTextField jtxtApellidos2;
    private javax.swing.JTextField jtxtApodo;
    private javax.swing.JTextField jtxtCargo;
    private javax.swing.JTextField jtxtCiudad;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtDocumento;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtEstadoCiv;
    private javax.swing.JTextField jtxtFechaNac;
    private javax.swing.JTextField jtxtGenero;
    private javax.swing.JTextField jtxtNombreEmpresa;
    private javax.swing.JTextField jtxtNombres1;
    private javax.swing.JTextField jtxtNombres2;
    private javax.swing.JTextField jtxtParentesco;
    private javax.swing.JTextField jtxtProfesion;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
